services:
  vancouver:
    build: .
    image: worktrial-sre:latest
    ports: ["8001:80"]
    environment: { LOCATION: vancouver, VERSION: v1, BASE_LATENCY_MS: "300" }
  toronto:
    image: worktrial-sre:latest
    ports: ["8002:80"]
    environment: { LOCATION: toronto, VERSION: v1, BASE_LATENCY_MS: "400" }
  london:
    image: worktrial-sre:latest
    ports: ["8003:80"]
    environment: { LOCATION: london, VERSION: v1, BASE_LATENCY_MS: "500" }
  frankfurt:
    image: worktrial-sre:latest
    ports: ["8004:80"]
    environment: { LOCATION: frankfurt, VERSION: v1, BASE_LATENCY_MS: "450" }
  singapore:
    image: worktrial-sre:latest
    ports: ["8005:80"]
    environment: { LOCATION: singapore, VERSION: v1, BASE_LATENCY_MS: "600" }
